name = "rvy/git_rbx_studio_resolver"
version = "0.1.0"
private = true

[engines]
pesde = "^0.7.2"

[target]
environment = "roblox"

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
argparse = { name = "caveful_games/argparse", version = "=0.1.2", target = "lune" }
miu = { wally = "revvy02/miu", version = "^0.4.0" }
miu_ui_labs = { wally = "revvy02/miu-ui-labs", version = "^0.5.0" }
miu_virtual_list = { wally = "revvy02/miu-virtual-list", version = "^0.4.1" }
miu_wind = { wally = "revvy02/miu-wind", version = "^0.5.0" }
miu_px = { wally = "revvy02/miu-px", version = "^0.2.0" }
jecs = { wally = "ukendio/jecs", version = "^0.11.0" }
planck = { wally = "yetanotherclown/planck", version = "^0.3.0-rc.2" }
planck_run_service = { wally = "yetanotherclown/planck-runservice", version = "^0.3.0-rc.1" }
