import { useState, useEffect, useCallback } from 'react';
import type { TreeNode, Meta, DiffEntry, Property, ClassIcons } from '../types/api';

// Property with diff information
export interface DiffProperty {
  property: Property;
  diffType: 'added' | 'removed' | 'changed' | 'unchanged';
  oldProperty?: Property; // For 'changed' - the old value
}

// Re-export RefInfo from properties for convenience
export type { RefInfo } from '../types/properties';
import type { RefInfo } from '../types/properties';

// Raw core data from compressed JSON (no refInfo — built from tree)
interface RawCoreData {
  meta: Meta;
  oldTree: TreeNode;
  newTree: TreeNode;
  diffs: DiffEntry[];
  classIcons: ClassIcons;
}

// Core data with computed refInfo
interface CoreData extends RawCoreData {
  oldRefInfo: Record<string, RefInfo>;
  newRefInfo: Record<string, RefInfo>;
}


// Window globals
declare global {
  interface Window {
    __DIFF_DATA_B64__?: string;
    __OLD_PROPS_B64__?: string;
    __NEW_PROPS_B64__?: string;
  }
}

// Cached decompressed data
let coreDataCache: CoreData | null = null;
let coreDataPromise: Promise<CoreData> | null = null;

// Property caches (diff-only, small)
let oldPropsCache: Record<string, Property[]> | null = null;
let newPropsCache: Record<string, Property[]> | null = null;
let propsPromise: Map<string, Promise<void>> = new Map();

// Decompress gzip base64 data
async function decompressGzipBase64(base64: string): Promise<string> {
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }

  // Use DecompressionStream API (available in modern browsers)
  const ds = new DecompressionStream('gzip');
  const writer = ds.writable.getWriter();
  writer.write(bytes);
  writer.close();

  const reader = ds.readable.getReader();
  const chunks: Uint8Array[] = [];

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    chunks.push(value);
  }

  const totalLength = chunks.reduce((acc, chunk) => acc + chunk.length, 0);
  const result = new Uint8Array(totalLength);
  let offset = 0;
  for (const chunk of chunks) {
    result.set(chunk, offset);
    offset += chunk.length;
  }

  return new TextDecoder().decode(result);
}

// Load and decompress properties for a side on demand
async function ensurePropsLoaded(side: 'old' | 'new'): Promise<void> {
  const cache = side === 'old' ? oldPropsCache : newPropsCache;
  if (cache) return;

  const key = side;
  if (propsPromise.has(key)) {
    await propsPromise.get(key);
    return;
  }

  const promise = (async () => {
    const b64 = side === 'old' ? window.__OLD_PROPS_B64__ : window.__NEW_PROPS_B64__;
    if (!b64) return;

    const json = await decompressGzipBase64(b64);
    const data = JSON.parse(json);

    if (side === 'old') {
      oldPropsCache = data;
      window.__OLD_PROPS_B64__ = undefined; // Free memory
    } else {
      newPropsCache = data;
      window.__NEW_PROPS_B64__ = undefined;
    }
  })();

  propsPromise.set(key, promise);
  await promise;
  propsPromise.delete(key);
}

// Get properties for a ref
export async function getProperties(ref: string, side: 'old' | 'new'): Promise<Property[] | null> {
  await ensurePropsLoaded(side);
  const cache = side === 'old' ? oldPropsCache : newPropsCache;
  return cache?.[ref] ?? null;
}

// Build refInfo index from tree (ref -> {name, path, class})
function buildRefInfo(tree: TreeNode, parentPath: string = ''): Record<string, RefInfo> {
  const result: Record<string, RefInfo> = {};
  const path = parentPath ? `${parentPath}/${tree.name}` : tree.name;
  result[tree.ref] = { name: tree.name, path, class: tree.class };
  if (tree.children) {
    for (const child of tree.children) {
      Object.assign(result, buildRefInfo(child, path));
    }
  }
  return result;
}

// Get embedded core data (async — decompresses on first call)
async function getCoreData(): Promise<CoreData> {
  if (coreDataCache) return coreDataCache;

  if (coreDataPromise) return coreDataPromise;

  coreDataPromise = (async () => {
    const b64 = window.__DIFF_DATA_B64__;
    if (!b64) {
      throw new Error('No embedded data found. This HTML must be generated by rbx-diff-viewer CLI.');
    }
    const json = await decompressGzipBase64(b64);
    const raw: RawCoreData = JSON.parse(json);
    // Build refInfo from tree data (saves 176MB in HTML)
    coreDataCache = {
      ...raw,
      oldRefInfo: buildRefInfo(raw.oldTree),
      newRefInfo: buildRefInfo(raw.newTree),
    };
    return coreDataCache!;
  })();

  return coreDataPromise;
}

// Check if embedded data exists
export function hasEmbeddedData(): boolean {
  return !!window.__DIFF_DATA_B64__;
}

// Hook to get core embedded data (decompresses on first use)
export function useEmbeddedData() {
  const [data, setData] = useState<CoreData | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    getCoreData()
      .then(setData)
      .catch(err => {
        setError(err instanceof Error ? err.message : 'Failed to load embedded data');
      });
  }, []);

  return { data, error };
}

// Check if files are loaded (always true for embedded)
export function useStatus() {
  return { data: { loaded: true }, loading: false, error: null };
}

// Get metadata
export function useMeta() {
  const { data } = useEmbeddedData();
  return { data: data?.meta ?? null, loading: !data, error: null };
}

// Get tree (returns full tree with all children pre-loaded)
export function useTree(side: 'old' | 'new') {
  const { data } = useEmbeddedData();
  const tree = side === 'old' ? data?.oldTree : data?.newTree;
  return { data: tree ?? null, loading: !data, error: null };
}

// Get diffs
export function useDiffs() {
  const { data } = useEmbeddedData();
  return { data: data?.diffs ?? null, loading: !data, error: null };
}

// Get class icons
export function useClassIcons() {
  const { data } = useEmbeddedData();
  return { data: data?.classIcons ?? {}, loading: !data, error: null };
}

// Get ref info map for a side
export function useRefInfo(side: 'old' | 'new') {
  const { data } = useEmbeddedData();
  const refInfo = side === 'old' ? data?.oldRefInfo : data?.newRefInfo;
  return { data: refInfo ?? {}, loading: !data, error: null };
}

// Fetch children from embedded data
export async function fetchChildren(ref: string, side: 'old' | 'new'): Promise<TreeNode[]> {
  const data = await getCoreData();
  const tree = side === 'old' ? data.oldTree : data.newTree;

  // Find the node with this ref in the tree
  function findNode(node: TreeNode): TreeNode | null {
    if (node.ref === ref) return node;
    for (const child of node.children || []) {
      const found = findNode(child);
      if (found) return found;
    }
    return null;
  }

  const node = findNode(tree);
  return node?.children || [];
}

// Fetch properties for an instance - lazy loaded
export function useProperties(ref: string | null, side: 'old' | 'new') {
  const [properties, setProperties] = useState<Property[] | null>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!ref) {
      setProperties(null);
      return;
    }

    setLoading(true);
    getProperties(ref, side)
      .then(props => {
        setProperties(props);
        setLoading(false);
      })
      .catch(err => {
        console.error('Failed to load properties:', err);
        setLoading(false);
      });
  }, [ref, side]);

  return { data: properties, loading, error: null };
}

// Upload is not supported in static mode
export function useUpload() {
  const upload = useCallback(async (): Promise<boolean> => {
    console.warn('Upload not supported in static HTML mode');
    return false;
  }, []);

  return { upload, loading: false, error: 'Upload not supported in static HTML mode' };
}

// Fetch properties for diff view - lazy loaded
export function useDiffProperties(diffEntry: DiffEntry | null) {
  const [result, setResult] = useState<DiffProperty[] | null>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!diffEntry) {
      setResult(null);
      return;
    }

    setLoading(true);

    (async () => {
      try {
        if (diffEntry.type === 'added' && diffEntry.new_ref) {
          const properties = await getProperties(diffEntry.new_ref, 'new') || [];
          setResult(properties.map(p => ({ property: p, diffType: 'added' as const })));

        } else if (diffEntry.type === 'removed' && diffEntry.old_ref) {
          const properties = await getProperties(diffEntry.old_ref, 'old') || [];
          setResult(properties.map(p => ({ property: p, diffType: 'removed' as const })));

        } else if (diffEntry.type === 'modified' && diffEntry.new_ref) {
          const newProps = await getProperties(diffEntry.new_ref, 'new') || [];
          const oldPropsMap = new Map<string, Property>();

          if (diffEntry.old_ref) {
            const oldProps = await getProperties(diffEntry.old_ref, 'old') || [];
            for (const p of oldProps) {
              oldPropsMap.set(p.name, p);
            }
          }

          // Build a set of changed property names
          const changedNames = new Set<string>();
          if (diffEntry.property_changes) {
            for (const change of diffEntry.property_changes) {
              changedNames.add(change.name);
            }
          }

          const resultProps: DiffProperty[] = [];

          // Categorize each new property
          for (const prop of newProps) {
            if (changedNames.has(prop.name)) {
              const oldProp = oldPropsMap.get(prop.name);
              resultProps.push({
                property: prop,
                diffType: 'changed',
                oldProperty: oldProp
              });
              changedNames.delete(prop.name);
            } else {
              resultProps.push({ property: prop, diffType: 'unchanged' });
            }
          }

          // Any remaining changed names that weren't in new properties are removed
          for (const name of changedNames) {
            const oldProp = oldPropsMap.get(name);
            if (oldProp) {
              resultProps.push({ property: oldProp, diffType: 'removed' });
            }
          }

          setResult(resultProps);
        }
      } catch (err) {
        console.error('Failed to load diff properties:', err);
      } finally {
        setLoading(false);
      }
    })();
  }, [diffEntry]);

  return { data: result, loading, error: null };
}
