import { useState, useEffect, useCallback } from 'react';
import type { TreeNode, Meta, DiffEntry, Property, ClassIcons } from '../types/api';

// Property with diff information
export interface DiffProperty {
  property: Property;
  diffType: 'added' | 'removed' | 'changed' | 'unchanged';
  oldProperty?: Property; // For 'changed' - the old value
}

// Re-export RefInfo from properties for convenience
export type { RefInfo } from '../types/properties';
import type { RefInfo } from '../types/properties';

// Core embedded data (parsed immediately - no properties)
interface CoreData {
  meta: Meta;
  oldTree: TreeNode;
  newTree: TreeNode;
  diffs: DiffEntry[];
  classIcons: ClassIcons;
  oldRefInfo: Record<string, RefInfo>;
  newRefInfo: Record<string, RefInfo>;
}


// Window globals
declare global {
  interface Window {
    __DIFF_DATA__?: CoreData;
    __OLD_PROPERTIES_B64__?: string;
    __NEW_PROPERTIES_B64__?: string;
  }
}

// Cached decompressed properties
let oldPropertiesCache: Record<string, Property[]> | null = null;
let newPropertiesCache: Record<string, Property[]> | null = null;
let decompressPromise: Promise<void> | null = null;

// Decompress gzip base64 data
async function decompressGzipBase64(base64: string): Promise<string> {
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }

  // Use DecompressionStream API (available in modern browsers)
  const ds = new DecompressionStream('gzip');
  const writer = ds.writable.getWriter();
  writer.write(bytes);
  writer.close();

  const reader = ds.readable.getReader();
  const chunks: Uint8Array[] = [];

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    chunks.push(value);
  }

  const totalLength = chunks.reduce((acc, chunk) => acc + chunk.length, 0);
  const result = new Uint8Array(totalLength);
  let offset = 0;
  for (const chunk of chunks) {
    result.set(chunk, offset);
    offset += chunk.length;
  }

  return new TextDecoder().decode(result);
}

// Lazy load and decompress properties
async function ensurePropertiesLoaded(): Promise<void> {
  if (oldPropertiesCache && newPropertiesCache) return;

  if (decompressPromise) {
    await decompressPromise;
    return;
  }

  decompressPromise = (async () => {
    const oldB64 = window.__OLD_PROPERTIES_B64__;
    const newB64 = window.__NEW_PROPERTIES_B64__;

    if (oldB64 && !oldPropertiesCache) {
      const json = await decompressGzipBase64(oldB64);
      oldPropertiesCache = JSON.parse(json);
    }

    if (newB64 && !newPropertiesCache) {
      const json = await decompressGzipBase64(newB64);
      newPropertiesCache = JSON.parse(json);
    }
  })();

  await decompressPromise;
}

// Get properties for a ref (lazy loads if needed)
export async function getProperties(ref: string, side: 'old' | 'new'): Promise<Property[] | null> {
  await ensurePropertiesLoaded();
  const cache = side === 'old' ? oldPropertiesCache : newPropertiesCache;
  return cache?.[ref] ?? null;
}

// Get embedded core data from window
function getCoreData(): CoreData {
  const data = window.__DIFF_DATA__;
  if (!data) {
    throw new Error('No embedded data found. This HTML must be generated by rbx-diff-viewer CLI.');
  }
  return data;
}

// Check if embedded data exists
export function hasEmbeddedData(): boolean {
  return !!window.__DIFF_DATA__;
}

// Hook to get core embedded data (fast, no properties)
export function useEmbeddedData() {
  const [data, setData] = useState<CoreData | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    try {
      setData(getCoreData());
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load embedded data');
    }
  }, []);

  return { data, error };
}

// Check if files are loaded (always true for embedded)
export function useStatus() {
  return { data: { loaded: true }, loading: false, error: null };
}

// Get metadata
export function useMeta() {
  const { data } = useEmbeddedData();
  return { data: data?.meta ?? null, loading: !data, error: null };
}

// Get tree (returns full tree with all children pre-loaded)
export function useTree(side: 'old' | 'new') {
  const { data } = useEmbeddedData();
  const tree = side === 'old' ? data?.oldTree : data?.newTree;
  return { data: tree ?? null, loading: !data, error: null };
}

// Get diffs
export function useDiffs() {
  const { data } = useEmbeddedData();
  return { data: data?.diffs ?? null, loading: !data, error: null };
}

// Get class icons
export function useClassIcons() {
  const { data } = useEmbeddedData();
  return { data: data?.classIcons ?? {}, loading: !data, error: null };
}

// Get ref info map for a side
export function useRefInfo(side: 'old' | 'new') {
  const { data } = useEmbeddedData();
  const refInfo = side === 'old' ? data?.oldRefInfo : data?.newRefInfo;
  return { data: refInfo ?? {}, loading: !data, error: null };
}

// Fetch children - now synchronous from embedded data
export async function fetchChildren(ref: string, side: 'old' | 'new'): Promise<TreeNode[]> {
  const data = getCoreData();
  const tree = side === 'old' ? data.oldTree : data.newTree;

  // Find the node with this ref in the tree
  function findNode(node: TreeNode): TreeNode | null {
    if (node.ref === ref) return node;
    for (const child of node.children || []) {
      const found = findNode(child);
      if (found) return found;
    }
    return null;
  }

  const node = findNode(tree);
  return node?.children || [];
}

// Fetch properties for an instance - lazy loaded
export function useProperties(ref: string | null, side: 'old' | 'new') {
  const [properties, setProperties] = useState<Property[] | null>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!ref) {
      setProperties(null);
      return;
    }

    setLoading(true);
    getProperties(ref, side)
      .then(props => {
        setProperties(props);
        setLoading(false);
      })
      .catch(err => {
        console.error('Failed to load properties:', err);
        setLoading(false);
      });
  }, [ref, side]);

  return { data: properties, loading, error: null };
}

// Upload is not supported in static mode
export function useUpload() {
  const upload = useCallback(async (): Promise<boolean> => {
    console.warn('Upload not supported in static HTML mode');
    return false;
  }, []);

  return { upload, loading: false, error: 'Upload not supported in static HTML mode' };
}

// Fetch properties for diff view - lazy loaded
export function useDiffProperties(diffEntry: DiffEntry | null) {
  const [result, setResult] = useState<DiffProperty[] | null>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!diffEntry) {
      setResult(null);
      return;
    }

    setLoading(true);

    (async () => {
      try {
        if (diffEntry.type === 'added' && diffEntry.new_ref) {
          const properties = await getProperties(diffEntry.new_ref, 'new') || [];
          setResult(properties.map(p => ({ property: p, diffType: 'added' as const })));

        } else if (diffEntry.type === 'removed' && diffEntry.old_ref) {
          const properties = await getProperties(diffEntry.old_ref, 'old') || [];
          setResult(properties.map(p => ({ property: p, diffType: 'removed' as const })));

        } else if (diffEntry.type === 'modified' && diffEntry.new_ref) {
          const newProps = await getProperties(diffEntry.new_ref, 'new') || [];
          const oldPropsMap = new Map<string, Property>();

          if (diffEntry.old_ref) {
            const oldProps = await getProperties(diffEntry.old_ref, 'old') || [];
            for (const p of oldProps) {
              oldPropsMap.set(p.name, p);
            }
          }

          // Build a set of changed property names
          const changedNames = new Set<string>();
          if (diffEntry.property_changes) {
            for (const change of diffEntry.property_changes) {
              changedNames.add(change.name);
            }
          }

          const resultProps: DiffProperty[] = [];

          // Categorize each new property
          for (const prop of newProps) {
            if (changedNames.has(prop.name)) {
              const oldProp = oldPropsMap.get(prop.name);
              resultProps.push({
                property: prop,
                diffType: 'changed',
                oldProperty: oldProp
              });
              changedNames.delete(prop.name);
            } else {
              resultProps.push({ property: prop, diffType: 'unchanged' });
            }
          }

          // Any remaining changed names that weren't in new properties are removed
          for (const name of changedNames) {
            const oldProp = oldPropsMap.get(name);
            if (oldProp) {
              resultProps.push({ property: oldProp, diffType: 'removed' });
            }
          }

          setResult(resultProps);
        }
      } catch (err) {
        console.error('Failed to load diff properties:', err);
      } finally {
        setLoading(false);
      }
    })();
  }, [diffEntry]);

  return { data: result, loading, error: null };
}
